import { STARTING_TPE } from '../../lib/constants';

export type ChangeTypes = 'Render' | 'Position' | 'Name' | 'KitNumber';

export type ActivityTypes =
    | 'Training'
    | 'Activity Check'
    | 'Training Camp';

// Sets the different types of player based on their career timeline
export const PLAYER_TASK_STATUSES = [
    'Academy Player',
    'SSL',
    'Everyone',
] as const;

export type PlayerTaskStatus = (typeof PLAYER_TASK_STATUSES)[number];

export const PLAYER_TASK_STATUS = {
    ACADEMY: 'Academy Player',
    SSL: 'SSL',
} as const;

export const POSITIONS = [
    'Striker',
    'Left Attacking Midfielder',
    'Central Attacking Midfielder',
    'Right Attacking Midfielder',
    'Left Midfielder',
    'Central Midfielder',
    'Right Midfielder',
    'Left Wing Back',
    'Central Defensive Midfielder',
    'Right Wing Back',
    'Left Defender',
    'Central Defender',
    'Right Defender',
    'Goalkeeper',
] as const;

export type Position = (typeof POSITIONS)[number];

export const TRAITS = [
    "Cuts Inside From Both Wings",
    "Knocks Ball Past Opponent",
    "Runs With Ball Rarely",
    "Runs With Ball Often",
    "Runs With Ball Down Left",
    "Runs With Ball Down Right",
    "Runs With Ball Through Centre",
    "Stops Play",
    "Brings Ball Out Of Defense",

    "Arrives Late In Opponent's Area",
    "Comes Deep To Get Ball",
    "Gets Forward Whenever Possible",
    "Gets Into Opposition Area",
    "Hugs Line",
    "Likes To Try To Beat Offside Trap",
    "Moves Into Channels",
    "Plays One-Twos",
    "Plays With Back To Goal",
    "Does Not Move Into Channels",
    "Stays Back At All Times",
    "Likes Ball Played To Feet",

    "Dictates Tempo",
    "Likes To Switch Ball To Other Flank",
    "Looks For Pass Rather Than Attempting To Score",
    "Plays No Through Balls",
    "Plays Short Simple Passes",
    "Tries Killer Balls Often",
    "Tries Long Range Passes",
    "Crossing Early",

    "Attempts Overhead Kicks",
    "Hits Free Kicks With Power",
    "Likes To Lob Keeper",
    "Likes To Round Keeper",
    "Places Shots",
    "Refrains From Taking Long Shots",
    "Shoots From Distance",
    "Shoots With Power",
    "Tries First Time Shots",
    "Tries Long Range Free Kicks",

    "Argues With Officials",
    "Winds Up Opponents",
    "Gets Crowd Going",

    "Dives Into Tackles",
    "Does Not Dive Into Tackles",
    "Marks Opponent Tightly",

    "Avoids Using Weaker Foot",
    "Uses Outside Of Foot",
    "Tries Tricks",
    "Likes To Beat Opponent Repeatedly",
    "Curls Ball",
    "Possess Long Flat Throw",
    "Tries To Play Way Out Of Trouble",

    "Uses Long Throw To Start Counter Attacks",
    "Plays Ball With Feet",
] as const;

export type Traits = (typeof TRAITS)[number];

const FOOTEDNESS = ['Left', 'Right'] as const;

export type FOOTEDNESS = (typeof FOOTEDNESS)[number];

export const COUNTRIES = [
    "Other",
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Côte d'Ivoire",
    "Democratic Republic of the Congo",
    "Republic of the Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "England",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea, North",
    "Korea, South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Macedonia",
    "Northern Ireland",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Scotland",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Wales",
    "Yemen",
    "Zambia",
    "Zimbabwe",
] as const;

// export const IIHF_COUNTRIES = {
//     0: 'Germany',
//     1: 'Great Britain',
//     2: 'Ireland',
//     4: 'France',
//     5: 'Canada',
//     6: 'Czechia',
//     7: 'Finland',
//     8: 'Independent Russia',
//     9: 'Sweden',
//     10: 'Switzerland',
//     11: 'USA',
//     12: 'Japan',
//     13: 'Latvia',
//     14: 'Norway',
// } as const;

export type Country = (typeof COUNTRIES)[number];

export const PLAYER_INFO_OPTIONS = {
    POSITIONS,
    TRAITS,
    FOOTEDNESS,
    COUNTRIES,
} as const;

export const PLAYER_DEFAULTS = {
    info: {
        firstName: '',
        lastName: '',
        position: 'Striker',
        footedness: 'Right',
        recruiter: '',
        render: '',
        kitNumber: 0,
        height: 62,
        weight: 200,
        birthplace: '', // List of Countries? / City
        totalTPE: STARTING_TPE,
    },
    goalie: {
        acceleration: 5,
        agility: 5,
        balance: 5,
        jumpingReach: 5,
        naturalFitness: 5,
        pace: 5,
        stamina: 5,
        strength: 5,
        aggression: 5,
        anticipation: 5,
        bravery: 5,
        composure: 5,
        concentration: 5,
        decisions: 5,
        determination: 5,
        flair: 5,
        leadership: 5,
        offTheBall: 5,
        positioning: 5,
        teamWork: 5,
        vision: 5,
        workRate: 5,
        aerialReach: 5,
        commandOfArea: 5,
        communication: 5,
        eccentricity: 5,
        handling: 5,
        kicking: 5,
        oneOnOnes: 5,
        reflexes: 5,
        tendencyToRush: 5,
        tendencyToPunch: 5,
        throwing: 5,
        firstTouch: 5,
        freeKick: 5,
        passing: 5,
        penaltyTaking: 5,
        technique: 5,
    },
    outfield: {
        acceleration: 5,
        agility: 5,
        balance: 5,
        jumpingReach: 5,
        naturalFitness: 20,
        pace: 5,
        stamina: 20,
        strength: 5,
        aggression: 5,
        anticipation: 5,
        bravery: 5,
        composure: 5,
        concentration: 5,
        decisions: 5,
        determination: 5,
        flair: 5,
        leadership: 5,
        offTheBall: 5,
        positioning: 5,
        teamWork: 5,
        vision: 5,
        workRate: 5,
        corners: 5,
        crossing: 5,
        dribbling: 5,
        finishing: 5,
        firstTouch: 5,
        freeKick: 5,
        heading: 5,
        longShots: 5,
        longThrows: 5,
        marking: 5,
        passing: 5,
        penaltyTaking: 5,
        tackling: 5,
        technique: 5,
    },
    availableTPE: STARTING_TPE,
} as const;

export type LimitedAttribute = {
    min: number;
    max: number;
    positions: Position[];
};

export type AttributeCosts = {
    pointCost: number;
    totalCost: number;
};

export const ATTRIBUTE_LABEL_TOOLTIPS = {
    acceleration: "The player's ability to quickly reach their top speed.",
    agility: "The player's ability to quickly change direction in their movement.",
    balance: "The player's ability to hold their balance when being subjected to physical pressure.",
    jumpingReach: "The maximum height a player can reach when jumping.",
    naturalFitness: "Locked at 20.",
    pace: "The player's top speed.",
    stamina: "Locked at 20.",
    strength: "The player's ability to put physical pressure on another player.",
    aggression: 'The likelihood of the player to get into physical situations and the amount of force they use.',
    anticipation: 'The player\'s ability to anticipate teammates\' and opposition movements and actions.',
    bravery: 'The willingness of the player to get into areas where they risk an injury.',
    composure: 'The player\'s ability to remain unaffected while being under mental pressure.',
    concentration: 'The player\'s ability to keep focus later in the game.',
    decisions: 'The player\'s ability to decide the best action to perform throughout a game.',
    determination: 'The willingness of the player to try and perform even when their team is losing or the player is not performing well.',
    flair: 'The player\'s ability to do something unexpected with the ball.',
    leadership: 'How inspirational and motivational a player is to their teammates.',
    offTheBall: 'The player\'s ability to do position themselves while their team has possession (Offensive).',
    positioning: 'The player\'s ability to position themselves while the opposing team has possession (Defensive).',
    teamWork: 'The player\'s ability to follow tactical instructions and the positions of other players on the pitch.',
    vision: 'The player\'s ability to see what opportunities exist while in possession of the ball.',
    workRate: 'The player\'s amount of physical effort that is used during the match.',
    corners: 'The player\'s ability to hit the intended target off a corner.',
    crossing: 'The player\'s ability to hit the intended target when crossing the ball from the wide areas of the pitch.',
    dribbling: 'The player\'s ability to control the ball while moving.',
    finishing: 'The player\'s ability to hit the intended target of the goal with a shot.',
    firstTouch: 'The player\'s ability to control and set up the ball after receiving it.',
    freeKick: 'The player\'s ability to hit the intended target with a free kick.',
    heading: 'The player\'s ability to hit the intended target with a header.',
    longShots: 'The player\'s ability to hit the intended target with a shot from outside the opposition\'s penalty area.',
    longThrows: 'The length a player can throw the ball and the player\'s ability to hit the intended target with a long throw.',
    marking: 'The player\'s ability to mark an opponent.',
    passing: 'The player\'s ability to hit their intended target with a pass.',
    penaltyTaking: 'The player\'s ability to hit their intended target on a penalty kick.',
    tackling: 'The player\'s ability to get the ball from the opponent without incurring a foul.',
    technique: 'The player\'s ability to successfully perform advanced technical actions.',
    aerialReach: 'The height a goalkeeper can reach when jumping. Equivalent to outfielders Jumping Reach.',
    commandOfArea: 'The ability to take control of balls in the box.',
    communication: 'The ability to communicate with teammates and control the defensive organization.',
    eccentricity: 'The likelihood to do something unexpected or risky.',
    handling: 'The ability to keep control of the ball when catching it.',
    kicking: 'The maximum length of a kick.',
    oneOnOnes: 'The ability to perform well when alone with an opponent.',
    reflexes: 'The ability to react to shots.',
    tendencyToRush: 'The ability to assess when to rush out.',
    tendencyToPunch: 'The likelihood to punch instead of catching the ball.',
    throwing: 'The ability to hit the intended target when throwing the ball.',
} as const;

// Striker Roles
const AdvancedForwardA = 'Advanced Forward - Attack';
const CompleteForwardA = 'Complete Forward - Attack';
const CompleteForwardS = 'Complete Forward - Support';
const DeepLyingForwardA = 'Deep Lying Forward - Attack';
const DeepLyingForwardS = 'Deep Lying Forward - Support';
const False9S = 'False 9 - Support';
const PoacherA = 'Poacher - Attack';
const PressingForwardA = 'Pressing Forward - Attack';
const PressingForwardS = 'Pressing Forward - Support';
const PressingForwardD = 'Pressing Forward - Defend';
const TrequartistaA = 'Trequartista - Attack';
const TargetPlayerA = 'Target Player - Attack';
const TargetPlayerS = 'Target Player - Support';

export const STRIKER_ROLES = [
    AdvancedForwardA,
    CompleteForwardA,
    CompleteForwardS,
    DeepLyingForwardA,
    DeepLyingForwardS,
    False9S,
    PoacherA,
    PressingForwardA,
    PressingForwardS,
    PressingForwardD,
    TrequartistaA,
    TargetPlayerA,
    TargetPlayerS,
] as const;

// Midfielder Roles
const AnchorD = 'Anchor - Defend';
const BallWinningMidfielderD = 'Ball Winning Midfielder - Defend';
const BallWinningMidfielderS = 'Ball Winning Midfielder - Support';
const DefensiveMidfielderD = 'Defensive Midfielder - Defend';
const DefensiveMidfielderS = 'Defensive Midfielder - Support';
const DeepLyingPlaymakerD = 'Deep Lying Playmaker - Defend';
const DeepLyingPlaymakerS = 'Deep Lying Playmaker - Support';
const HalfBackD = 'Half Back - Defend';
const RegistaS = 'Regista - Support';
const RoamingPlaymakerS = 'Roaming Playmaker - Support';
const SegundoVolanteA = 'Segundo Volante - Attack';
const SegundoVolanteS = 'Segundo Volante - Support';
const AttackingMidfielderA = 'Attacking Midfielder - Attack';
const AttackingMidfielderS = 'Attacking Midfielder - Support';
const AdvancedPlaymakerA = 'Advanced Playmaker - Attack';
const AdvancedPlaymakerS = 'Advanced Playmaker - Support';
const EngancheS = 'Enganche - Support';
const ShadowStrikerA = 'Shadow Striker - Attack';
// const TrequartistaA = 'Trequartista - Attack';
const InsideForwardA = 'Inside Forward - Attack';
const InsideForwardS = 'Inside Forward - Support';
const InvertedWingerA = 'Inverted Winger - Attack';
const InvertedWingerS = 'Inverted Winger - Support';
const RaumdeuterA = 'Raumdeuter - Attack';
const WingerA = 'Winger - Attack';
const WingerS = 'Winger - Support';
const WideTargetPlayerA = 'Wide Target Player - Attack';
const WideTargetPlayerS = 'Wide Target Player - Support';
const BoxToBoxS = 'Box to Box - Support';
const CarrileroS = 'Carrilero - Support';
const CentralMidfielderA = 'Central Midfielder - Attack';
const CentralMidfielderD = 'Central Midfielder - Defend';
const CentralMidfielderS = 'Central Midfielder - Support';
const MezzalaA = 'Mezzala - Attack';
const MezzalaS = 'Mezzala - Support';
const DefensiveWingerD = 'Defensive Winger - Defend';
const DefensiveWingerS = 'Defensive Winger - Support';
const WideMidfielderA = 'Wide Midfielder - Attack';
const WideMidfielderD = 'Wide Midfielder - Defend';
const WideMidfielderS = 'Wide Midfielder - Support';
const WidePlaymakerA = 'Wide Playmaker - Attack';
const WidePlaymakerS = 'Wide Playmaker - Support';


export const MIDFIELDER_ROLES = [
    AnchorD,
    BallWinningMidfielderD,
    BallWinningMidfielderS,
    DefensiveMidfielderD,
    DefensiveMidfielderS,
    DeepLyingPlaymakerD,
    DeepLyingPlaymakerS,
    HalfBackD,
    RegistaS,
    RoamingPlaymakerS,
    SegundoVolanteA,
    SegundoVolanteS,
    AttackingMidfielderA,
    AttackingMidfielderS,
    AdvancedPlaymakerA,
    AdvancedPlaymakerS,
    EngancheS,
    ShadowStrikerA,
    TrequartistaA,
    InsideForwardA,
    InsideForwardS,
    InvertedWingerA,
    InvertedWingerS,
    RaumdeuterA,
    WingerA,
    WingerS,
    WideTargetPlayerA,
    WideTargetPlayerS,
    BoxToBoxS,
    CarrileroS,
    CentralMidfielderA,
    CentralMidfielderD,
    CentralMidfielderS,
    MezzalaA,
    MezzalaS,
    DefensiveWingerD,
    DefensiveWingerS,
    WideMidfielderA,
    WideMidfielderD,
    WideMidfielderS,
    WidePlaymakerA,
    WidePlaymakerS,
] as const;

// Defender Roles
const BallPlayingDefensemanC = 'Ball Playing Defenseman - Cover';
const BallPlayingDefensemanD = 'Ball Playing Defenseman - Defend';
const BallPlayingDefensemanS = 'Ball Playing Defenseman - Stopper';
const CentralDefenderC = 'Central Defender - Cover';
const CentralDefenderD = 'Central Defender - Defend';
const CentralDefenderS = 'Central Defender - Stopper';
const LiberoA = 'Libero - Attack';
const LiberoS = 'Libero - Support';
const NoNonsenseCenterBackC = 'No-nonsense Center Back - Cover';
const NoNonsenseCenterBackD = 'No-nonsense Center Back - Defend';
const NoNonsenseCenterBackS = 'No-nonsense Center Back - Stopper';
const CompleteWingBackA = 'Complete Wing Back - Attack';
const CompleteWingBackS = 'Complete Wing Back - Support';
const FullBackA = 'Full Back - Attack';
const FullBackD = 'Full Back - Defend';
const FullBackS = 'Full Back - Support';
const InvertedWingBackA = 'Inverted Wing Back - Attack';
const InvertedWingBackD = 'Inverted Wing Back - Defend';
const InvertedWingBackS = 'Inverted Wing Back - Support';
const NoNonsenseFullBackD = 'No-nonsense Full Back - Defend';
const WingBackA = 'Wing Back - Attack';
const WingBackD = 'Wing Back - Defend';
const WingBackS = 'Wing Back - Support';

export const DEFENDER_ROLES = [
    BallPlayingDefensemanC,
    BallPlayingDefensemanD,
    BallPlayingDefensemanS,
    CentralDefenderC,
    CentralDefenderD,
    CentralDefenderS,
    LiberoA,
    LiberoS,
    NoNonsenseCenterBackC,
    NoNonsenseCenterBackD,
    NoNonsenseCenterBackS,
    CompleteWingBackA,
    CompleteWingBackS,
    FullBackA,
    FullBackD,
    FullBackS,
    InvertedWingBackA,
    InvertedWingBackD,
    InvertedWingBackS,
    NoNonsenseFullBackD,
    WingBackA,
    WingBackD,
    WingBackS,
] as const;

// Keeper roles
const ShotStopperD = "Shot Stopper - Defend";
const SweeperKeeperA = "Sweeper Keeper - Attack";
const SweeperKeeperD = "Sweeper Keeper - Defend";
const SweeperKeeperS = "Sweeper Keeper - Support";

export const KEEPER_ROLES = [
    SweeperKeeperA,
    SweeperKeeperS,
    SweeperKeeperD,
    ShotStopperD,
] as const;


export type PlayerRole =
    | (typeof DEFENDER_ROLES)[number]
    | (typeof MIDFIELDER_ROLES)[number]
    | (typeof STRIKER_ROLES)[number]
    | (typeof KEEPER_ROLES)[number];

export const ROLE_ATTRIBUTES = {
    acceleration: [
        AttackingMidfielderA,
        AttackingMidfielderS,
        AdvancedPlaymakerA,
        AdvancedPlaymakerS,
        EngancheS,
        ShadowStrikerA,
        TrequartistaA,
        InsideForwardA,
        InsideForwardS,
        InvertedWingerA,
        InvertedWingerS,
        RaumdeuterA,
        WingerA,
        WingerS,
        WideTargetPlayerA,
        WideTargetPlayerS,
        BallPlayingDefensemanC,
        BallPlayingDefensemanD,
        BallPlayingDefensemanS,
        CentralDefenderC,
        CentralDefenderD,
        CentralDefenderS,
        LiberoA,
        LiberoS,
        NoNonsenseCenterBackC,
        NoNonsenseCenterBackD,
        NoNonsenseCenterBackS,
        CompleteWingBackA,
        CompleteWingBackS,
        FullBackA,
        FullBackD,
        FullBackS,
        InvertedWingBackA,
        InvertedWingBackD,
        InvertedWingBackS,
        NoNonsenseFullBackD,
        WingBackA,
        WingBackD,
        WingBackS,
        AnchorD,
        BallWinningMidfielderD,
        BallWinningMidfielderS,
        DefensiveMidfielderD,
        DefensiveMidfielderS,
        DeepLyingPlaymakerD,
        DeepLyingPlaymakerS,
        HalfBackD,
        RegistaS,
        RoamingPlaymakerS,
        SegundoVolanteA,
        SegundoVolanteS,
        BoxToBoxS,
        CarrileroS,
        CentralMidfielderA,
        CentralMidfielderD,
        CentralMidfielderS,
        MezzalaA,
        MezzalaS,
        DefensiveWingerD,
        DefensiveWingerS,
        WideMidfielderA,
        WideMidfielderD,
        WideMidfielderS,
        WidePlaymakerA,
        WidePlaymakerS,
        AdvancedForwardA,
        CompleteForwardA,
        CompleteForwardS,
        DeepLyingForwardA,
        DeepLyingForwardS,
        False9S,
        PoacherA,
        PressingForwardA,
        PressingForwardD,
        PressingForwardS,
        TargetPlayerA,
        TargetPlayerS,
    ],
    aerialReach: [
        ShotStopperD,
    ],
    aggression: [
        BallPlayingDefensemanS,
        CentralDefenderS,
        NoNonsenseCenterBackS,
        BallWinningMidfielderD,
        BallWinningMidfielderS,
        BallWinningMidfielderD,
        BallWinningMidfielderS,
        PressingForwardA,
        PressingForwardD,
        PressingForwardS,
    ],
    agility: [
        InsideForwardA,
        InsideForwardS,
        InvertedWingerA,
        InsideForwardA,
        InsideForwardS,
        InvertedWingerA,
        ShotStopperD,
        SweeperKeeperA,
        SweeperKeeperD,
        SweeperKeeperS,
        InvertedWingerA,
        InvertedWingerA,
        CompleteForwardA,
        CompleteForwardS,
        False9S,
    ],
    anticipation: [
        AttackingMidfielderA,
        AttackingMidfielderS,
        ShadowStrikerA,
        RaumdeuterA,
        RaumdeuterA,
        BallPlayingDefensemanC,
        CentralDefenderC,
        CentralDefenderS,
        LiberoA,
        LiberoS,
        NoNonsenseCenterBackC,
        FullBackA,
        FullBackD,
        FullBackS,
        InvertedWingBackD,
        NoNonsenseFullBackD,
        WingBackD,
        AnchorD,
        BallWinningMidfielderD,
        BallWinningMidfielderS,
        DefensiveMidfielderD,
        DefensiveMidfielderS,
        HalfBackD,
        RoamingPlaymakerS,
        SegundoVolanteA,
        FullBackA,
        FullBackD,
        FullBackS,
        InvertedWingBackD,
        NoNonsenseFullBackD,
        WingBackD,
        SweeperKeeperA,
        SweeperKeeperD,
        SweeperKeeperS,
        BallWinningMidfielderD,
        BallWinningMidfielderS,
        RoamingPlaymakerS,
        DefensiveWingerD,
        DefensiveWingerD,
        CompleteForwardA,
        CompleteForwardS,
        PoacherA,
        PressingForwardA,
        PressingForwardD,
        PressingForwardS,
        InvertedWingBackD,
        WingBackD,
        InvertedWingBackD,
        WingBackD,
    ],
    balance: [
        InsideForwardA,
        InsideForwardS,
        RaumdeuterA,
        InsideForwardA,
        InsideForwardS,
        RaumdeuterA,
        TargetPlayerA,
        TargetPlayerS,
    ],
    bravery: [
        WideTargetPlayerA,
        WideTargetPlayerS,
        BallPlayingDefensemanS,
        CentralDefenderS,
        NoNonsenseCenterBackS,
        BallWinningMidfielderD,
        BallWinningMidfielderS,
        PressingForwardA,
        PressingForwardD,
        PressingForwardS,
        TargetPlayerA,
        TargetPlayerS,
    ],
    commandOfArea: [
        ShotStopperD,
        SweeperKeeperA,
        SweeperKeeperD,
        SweeperKeeperS,
    ],
    communication: [
        ShotStopperD,
    ],
    composure: [
        AdvancedPlaymakerA,
        AdvancedPlaymakerS,
        EngancheS,
        ShadowStrikerA,
        TrequartistaA,
        RaumdeuterA,
        BallPlayingDefensemanC,
        BallPlayingDefensemanD,
        BallPlayingDefensemanS,
        LiberoA,
        LiberoS,
        DeepLyingPlaymakerD,
        DeepLyingPlaymakerS,
        RegistaS,
        RoamingPlaymakerS,
        SweeperKeeperA,
        SweeperKeeperS,
        WidePlaymakerA,
        WidePlaymakerS,
        AdvancedForwardA,
        CompleteForwardA,
        CompleteForwardS,
        DeepLyingForwardA,
        DeepLyingForwardS,
        False9S,
        PoacherA,
        TargetPlayerA,
    ],
    concentration: [
        RaumdeuterA,
        BallPlayingDefensemanC,
        CentralDefenderC,
        LiberoA,
        LiberoS,
        NoNonsenseCenterBackC,
        FullBackD,
        FullBackS,
        AnchorD,
        DefensiveMidfielderD,
        DefensiveMidfielderS,
        HalfBackD,
        ShotStopperD,
        SweeperKeeperA,
        SweeperKeeperD,
        SweeperKeeperS,
        CentralMidfielderD,
        WideMidfielderD
    ],
    corners: [],
    crossing: [
        WingerA,
        WingerS,
        CompleteWingBackA,
        CompleteWingBackS,
        FullBackA,
        WingBackA,
        WingBackS,
        DefensiveWingerS,
        WideMidfielderA
    ],
    decisions: [
        AttackingMidfielderA,
        AttackingMidfielderS,
        AdvancedPlaymakerA,
        AdvancedPlaymakerS,
        EngancheS,
        TrequartistaA,
        RaumdeuterA,
        BallPlayingDefensemanC,
        BallPlayingDefensemanS,
        CentralDefenderC,
        CentralDefenderS,
        LiberoA,
        LiberoS,
        CompleteWingBackA,
        CompleteWingBackS,
        InvertedWingBackA,
        InvertedWingBackD,
        InvertedWingBackS,
        AnchorD,
        DeepLyingPlaymakerD,
        DeepLyingPlaymakerS,
        RegistaS,
        RoamingPlaymakerS,
        CarrileroS,
        CentralMidfielderA,
        CentralMidfielderD,
        CentralMidfielderS,
        MezzalaA,
        MezzalaS,
        WideMidfielderA,
        WideMidfielderD,
        WideMidfielderS,
        WidePlaymakerA,
        WidePlaymakerS,
        CompleteForwardS,
        DeepLyingForwardA,
        DeepLyingForwardS,
        False9S,
        PressingForwardD,
        PressingForwardS,
        TrequartistaA
    ],
    determination: [],
    dribbling: [
        AttackingMidfielderA,
        AdvancedPlaymakerA,
        ShadowStrikerA,
        TrequartistaA,
        InsideForwardA,
        InsideForwardS,
        InvertedWingerA,
        InvertedWingerS,
        WingerA,
        WingerS,
        LiberoA,
        CompleteWingBackA,
        CompleteWingBackS,
        InvertedWingBackA,
        WingBackA,
        WingBackS,
        MezzalaA,
        WidePlaymakerA,
        AdvancedForwardA,
        CompleteForwardA,
        CompleteForwardS,
        False9S
    ],
    eccentricity: [],
    finishing: [
        ShadowStrikerA,
        InsideForwardA,
        RaumdeuterA,
        SegundoVolanteA,
        AdvancedForwardA,
        CompleteForwardA,
        PoacherA,
        TargetPlayerA
    ],
    firstTouch: [
        AttackingMidfielderA,
        AttackingMidfielderS,
        AdvancedPlaymakerA,
        AdvancedPlaymakerS,
        EngancheS,
        ShadowStrikerA,
        TrequartistaA,
        InsideForwardA,
        InsideForwardS,
        LiberoA,
        LiberoS,
        CompleteWingBackA,
        CompleteWingBackS,
        DeepLyingPlaymakerD,
        DeepLyingPlaymakerS,
        RegistaS,
        RoamingPlaymakerS,
        CentralMidfielderA,
        CentralMidfielderS,
        WideMidfielderA,
        WidePlaymakerA,
        WidePlaymakerS,
        AdvancedForwardA,
        CompleteForwardA,
        CompleteForwardS,
        DeepLyingForwardA,
        DeepLyingForwardS,
        False9S
    ],
    flair: [
        AttackingMidfielderA,
        AttackingMidfielderS,
        TrequartistaA,
        LiberoA,
        CompleteWingBackA,
        RegistaS
    ],
    freeKick: [],
    handling: [
        ShotStopperD
    ],
    heading: [
        WideTargetPlayerA,
        WideTargetPlayerS,
        BallPlayingDefensemanD,
        CentralDefenderD,
        NoNonsenseCenterBackD,
        CompleteForwardA,
        CompleteForwardS,
        TargetPlayerA,
        TargetPlayerS
    ],
    jumpingReach: [
        WideTargetPlayerA,
        WideTargetPlayerS,
        BallPlayingDefensemanD,
        BallPlayingDefensemanS,
        CentralDefenderD,
        CentralDefenderS,
        NoNonsenseCenterBackD,
        NoNonsenseCenterBackS,
        TargetPlayerA,
        TargetPlayerS
    ],
    kicking: [
        ShotStopperD,
        SweeperKeeperA,
        SweeperKeeperD,
        SweeperKeeperS,
    ],
    leadership: [],
    longShots: [
        AttackingMidfielderA,
        AttackingMidfielderS,
        SegundoVolanteA,
        CompleteForwardS
    ],
    longThrows: [],
    marking: [
        BallPlayingDefensemanC,
        BallPlayingDefensemanD,
        CentralDefenderC,
        CentralDefenderD,
        CentralDefenderS,
        LiberoA,
        LiberoS,
        NoNonsenseCenterBackC,
        NoNonsenseCenterBackD,
        FullBackD,
        FullBackS,
        InvertedWingBackA,
        InvertedWingBackD,
        InvertedWingBackS,
        NoNonsenseFullBackD,
        WingBackD,
        WingBackS,
        AnchorD,
        HalfBackD,
        SegundoVolanteS

    ],
    naturalFitness: [],
    offTheBall: [
        AttackingMidfielderA,
        AttackingMidfielderS,
        AdvancedPlaymakerA,
        AdvancedPlaymakerS,
        ShadowStrikerA,
        TrequartistaA,
        InsideForwardA,
        InsideForwardS,
        InvertedWingerA,
        InvertedWingerS,
        RaumdeuterA,
        WingerA,
        WingerS,
        WideTargetPlayerA,
        WideTargetPlayerS,
        CompleteWingBackA,
        CompleteWingBackS,
        InvertedWingBackA,
        InvertedWingBackS,
        WingBackA,
        WingBackS,
        RegistaS,
        RoamingPlaymakerS,
        SegundoVolanteA,
        BoxToBoxS,
        CentralMidfielderA,
        MezzalaA,
        MezzalaS,
        DefensiveWingerD,
        DefensiveWingerS,
        WidePlaymakerA,
        AdvancedForwardA,
        CompleteForwardA,
        CompleteForwardS,
        DeepLyingForwardA,
        False9S,
        PoacherA,
        PressingForwardA,
        TargetPlayerA
    ],
    oneOnOnes: [
        SweeperKeeperA,
        SweeperKeeperD,
        SweeperKeeperS
    ],
    pace: [
        WingerA,
        WingerS,
        BallPlayingDefensemanC,
        BallPlayingDefensemanD,
        CentralDefenderC,
        LiberoA,
        LiberoS,
        NoNonsenseCenterBackC,
        CompleteWingBackA,
        CompleteWingBackS,
        FullBackA,
        WingBackA,
        SegundoVolanteA,
        SegundoVolanteS,
        BoxToBoxS,
        PressingForwardA,
        PressingForwardD,
        PressingForwardS
    ],
    passing: [
        AttackingMidfielderA,
        AttackingMidfielderS,
        AdvancedPlaymakerA,
        AdvancedPlaymakerS,
        EngancheS,
        TrequartistaA,
        InsideForwardS,
        InvertedWingerA,
        InvertedWingerS,
        BallPlayingDefensemanC,
        BallPlayingDefensemanD,
        BallPlayingDefensemanS,
        LiberoA,
        LiberoS,
        CompleteWingBackA,
        CompleteWingBackS,
        InvertedWingBackA,
        InvertedWingBackD,
        InvertedWingBackS,
        DeepLyingPlaymakerD,
        DeepLyingPlaymakerS,
        RegistaS,
        RoamingPlaymakerS,
        SegundoVolanteA,
        SegundoVolanteS,
        BoxToBoxS,
        CarrileroS,
        CentralMidfielderA,
        CentralMidfielderS,
        MezzalaA,
        MezzalaS,
        WideMidfielderA,
        WideMidfielderD,
        WideMidfielderS,
        WidePlaymakerA,
        WidePlaymakerS,
        CompleteForwardS,
        DeepLyingForwardA,
        DeepLyingForwardS,
        False9S
    ],
    penaltyTaking: [],
    positioning: [
        BallPlayingDefensemanC,
        BallPlayingDefensemanD,
        BallPlayingDefensemanS,
        CentralDefenderC,
        CentralDefenderD,
        CentralDefenderS,
        LiberoA,
        LiberoS,
        NoNonsenseCenterBackC,
        NoNonsenseCenterBackD,
        NoNonsenseCenterBackS,
        FullBackA,
        FullBackD,
        FullBackS,
        InvertedWingBackD,
        NoNonsenseFullBackD,
        WingBackD,
        AnchorD,
        DefensiveMidfielderD,
        DefensiveMidfielderS,
        HalfBackD,
        SegundoVolanteA,
        SegundoVolanteS,
        CarrileroS,
        CentralMidfielderD,
        DefensiveWingerD,
        WideMidfielderD,
        ShotStopperD,
        SweeperKeeperA,
        SweeperKeeperD,
        SweeperKeeperS
    ],
    tendencyToPunch: [],
    reflexes: [
        ShotStopperD,
        SweeperKeeperA,
        SweeperKeeperD,
        SweeperKeeperS
    ],
    tendencyToRush: [
        SweeperKeeperA,
        SweeperKeeperS
    ],
    // No role importance due to it being fixed at 20.
    stamina: [],
    strength: [
        WideTargetPlayerA,
        WideTargetPlayerS,
        WideTargetPlayerA,
        WideTargetPlayerS,
        BallPlayingDefensemanD,
        BallPlayingDefensemanS,
        CentralDefenderD,
        NoNonsenseCenterBackD,
        NoNonsenseCenterBackS,
        NoNonsenseFullBackD,
        NoNonsenseFullBackD,
        CompleteForwardA,
        CompleteForwardS,
        TargetPlayerA,
        TargetPlayerS
    ],
    tackling: [
        BallPlayingDefensemanC,
        BallPlayingDefensemanD,
        BallPlayingDefensemanS,
        CentralDefenderC,
        CentralDefenderD,
        CentralDefenderS,
        LiberoA,
        LiberoS,
        NoNonsenseCenterBackC,
        NoNonsenseCenterBackD,
        NoNonsenseCenterBackS,
        FullBackA,
        FullBackD,
        FullBackS,
        InvertedWingBackA,
        InvertedWingBackD,
        InvertedWingBackS,
        NoNonsenseFullBackD,
        WingBackA,
        WingBackD,
        WingBackS,
        AnchorD,
        BallWinningMidfielderD,
        BallWinningMidfielderS,
        DefensiveMidfielderD,
        DefensiveMidfielderS,
        HalfBackD,
        SegundoVolanteA,
        SegundoVolanteS,
        BoxToBoxS,
        CarrileroS,
        CentralMidfielderD,
        CentralMidfielderS,
        WideMidfielderD,
        WideMidfielderS
    ],
    teamWork: [
        AdvancedPlaymakerA,
        AdvancedPlaymakerS,
        LiberoA,
        LiberoS,
        CompleteWingBackA,
        CompleteWingBackS,
        FullBackA,
        FullBackS,
        InvertedWingBackA,
        InvertedWingBackD,
        InvertedWingBackS,
        WingBackA,
        WingBackD,
        WingBackS,
        BallWinningMidfielderD,
        BallWinningMidfielderS,
        DefensiveMidfielderD,
        DefensiveMidfielderS,
        DeepLyingPlaymakerD,
        DeepLyingPlaymakerS,
        HalfBackD,
        RegistaS,
        RoamingPlaymakerS,
        BoxToBoxS,
        CarrileroS,
        CentralMidfielderD,
        CentralMidfielderS,
        DefensiveWingerD,
        DefensiveWingerS,
        WideMidfielderA,
        WideMidfielderD,
        WideMidfielderS,
        WidePlaymakerA,
        WidePlaymakerS,
        DeepLyingForwardA,
        DeepLyingForwardS,
        PressingForwardA,
        PressingForwardD,
        PressingForwardS,
        TargetPlayerS
    ],
    technique: [
        AttackingMidfielderA,
        AttackingMidfielderS,
        AdvancedPlaymakerA,
        AdvancedPlaymakerS,
        EngancheS,
        TrequartistaA,
        InsideForwardA,
        InsideForwardS,
        InvertedWingerA,
        InvertedWingerS,
        WingerA,
        WingerS,
        CompleteWingBackA,
        CompleteWingBackS,
        InvertedWingBackA,
        WingBackA,
        DeepLyingPlaymakerD,
        DeepLyingPlaymakerS,
        RegistaS,
        RoamingPlaymakerS,
        MezzalaA,
        MezzalaS,
        DefensiveWingerD,
        DefensiveWingerS,
        WidePlaymakerA,
        WidePlaymakerS,
        AdvancedForwardA,
        CompleteForwardA,
        CompleteForwardS,
        DeepLyingForwardA,
        DeepLyingForwardS,
        False9S
    ],
    throwing: [],
    vision: [
        AdvancedPlaymakerA,
        AdvancedPlaymakerS,
        EngancheS,
        TrequartistaA,
        LiberoA,
        LiberoS,
        DeepLyingPlaymakerD,
        DeepLyingPlaymakerS,
        RegistaS,
        RoamingPlaymakerS,
        MezzalaA,
        WidePlaymakerA,
        WidePlaymakerS,
        CompleteForwardS,
        False9S
    ],
    workRate: [
        CompleteWingBackA,
        CompleteWingBackS,
        FullBackA,
        FullBackS,
        InvertedWingBackA,
        InvertedWingBackD,
        InvertedWingBackS,
        WingBackA,
        WingBackD,
        WingBackS,
        BallWinningMidfielderD,
        BallWinningMidfielderS,
        DefensiveMidfielderD,
        DefensiveMidfielderS,
        DeepLyingPlaymakerD,
        HalfBackD,
        RoamingPlaymakerS,
        SegundoVolanteA,
        SegundoVolanteS,
        BoxToBoxS,
        CarrileroS,
        MezzalaA,
        MezzalaS,
        DefensiveWingerD,
        DefensiveWingerS,
        WideMidfielderA,
        WideMidfielderD,
        WideMidfielderS,
        PressingForwardA,
        PressingForwardD,
        PressingForwardS
    ],

};